spring:
  datasource:
    url: jdbc:mysql://hselfweb.cn:3306/jpcnbbs?serverTimezone=CTT
    username: jpcnbbs
    password: 123456
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  address:
  port: 8080
